import { existsSync } from "node:fs";
import { cp, mkdir, mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import extract from "extract-zip";
import type { AppEntry } from "../types.js";
import { downloadFile, verifyGithubReleaseChecksum } from "./downloadUtils.js";

const REPO = "matomo-org/matomo";

/**
 * Downloads the official Matomo zip distribution from its GitHub release,
 * verifies it against the sha256 digest GitHub publishes for the asset, and
 * overlays it onto appsDir/app.folder.
 *
 * config/config.ini.php (the site's real config, generated by the installer
 * - not shipped in the archive) is never overwritten if it already exists.
 * Nothing outside the new archive is deleted - this is a merge/overlay, not
 * a mirror, so tmp/ and other local files are left alone.
 *
 * Unlike the other appliers' archives, Matomo's zip root also contains a
 * stray "How to install Matomo.html" file alongside the real "matomo/"
 * directory, so the source folder has to be picked out as the top-level
 * directory entry rather than assumed to be the first readdir() result.
 */
export async function applyMatomoUpdate(
  app: AppEntry,
  appsDir: string,
  newVersion: string,
): Promise<void> {
  const workDir = await mkdtemp(path.join(tmpdir(), "matomo-update-"));

  try {
    const archiveName = `matomo-${newVersion}.zip`;
    const archiveUrl = `https://github.com/${REPO}/releases/download/${newVersion}/${archiveName}`;
    const archivePath = path.join(workDir, archiveName);

    await downloadFile(archiveUrl, archivePath);
    await verifyGithubReleaseChecksum(REPO, newVersion, archiveName, archivePath);

    const extractDir = path.join(workDir, "extracted");
    await mkdir(extractDir);
    await extract(archivePath, { dir: extractDir });

    const entries = await readdir(extractDir, { withFileTypes: true });
    const topLevelEntry = entries.find((entry) => entry.isDirectory())?.name;
    if (!topLevelEntry) {
      throw new Error(`Archive ${archiveName} did not contain a top-level directory`);
    }

    const sourceDir = path.join(extractDir, topLevelEntry);
    const targetDir = path.join(appsDir, app.folder);

    await cp(sourceDir, targetDir, {
      recursive: true,
      force: true,
      filter: (source) => {
        const relative = path.relative(sourceDir, source);
        if (relative !== path.join("config", "config.ini.php")) return true;
        return !existsSync(path.join(targetDir, relative));
      },
    });
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}
