import { existsSync } from "node:fs";
import { cp, mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import extract from "extract-zip";
import type { AppEntry } from "../types.js";
import { downloadFile, verifyGithubReleaseChecksum } from "./downloadUtils.js";

const REPO = "mautic/mautic";

/**
 * Downloads the official Mautic zip distribution from its GitHub release
 * (the plain "<version>.zip" asset - not the "<version>-update.zip" delta
 * package Mautic's own in-place upgrader uses), verifies it against the
 * sha256 digest GitHub publishes for the asset, and overlays it onto
 * appsDir/app.folder.
 *
 * Unlike the other appliers' archives, this one has no single wrapping
 * top-level directory - it extracts flat, with app/, config/, vendor/, etc.
 * directly at the archive root - so the extracted directory is used as the
 * source as-is.
 *
 * .env.local (Symfony's convention for the site's real local secrets - DB
 * credentials, app secret - generated by the installer and never shipped in
 * the archive, which only has the generic template ".env") is never
 * overwritten if it already exists. Nothing outside the new archive is
 * deleted - this is a merge/overlay, not a mirror, so var/ and other local
 * files are left alone.
 */
export async function applyMauticUpdate(
  app: AppEntry,
  appsDir: string,
  newVersion: string,
): Promise<void> {
  const workDir = await mkdtemp(path.join(tmpdir(), "mautic-update-"));

  try {
    const archiveName = `${newVersion}.zip`;
    const archiveUrl = `https://github.com/${REPO}/releases/download/${newVersion}/${archiveName}`;
    const archivePath = path.join(workDir, archiveName);

    await downloadFile(archiveUrl, archivePath);
    await verifyGithubReleaseChecksum(REPO, newVersion, archiveName, archivePath);

    const sourceDir = path.join(workDir, "extracted");
    await mkdir(sourceDir);
    await extract(archivePath, { dir: sourceDir });

    const targetDir = path.join(appsDir, app.folder);

    await cp(sourceDir, targetDir, {
      recursive: true,
      force: true,
      filter: (source) => {
        const relative = path.relative(sourceDir, source);
        if (relative !== ".env.local") return true;
        return !existsSync(path.join(targetDir, relative));
      },
    });
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}
