import { existsSync } from "node:fs";
import { cp, mkdir, mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import extract from "extract-zip";
import type { AppEntry } from "../types.js";
import { assertChecksum, downloadFile, sha256File } from "./downloadUtils.js";

const DIST_BASE = "https://download.nextcloud.com/server/releases";

/**
 * Downloads the official Nextcloud server zip distribution, verifies its
 * published sha256 checksum, and overlays it onto appsDir/app.folder.
 *
 * config/config.php (the site's real config, generated by the installer -
 * not shipped in the archive, which only has config.sample.php) is never
 * overwritten if it already exists. Nothing outside the new archive is
 * deleted - this is a merge/overlay, not a mirror, so the data/ directory
 * and other local files are left alone.
 */
export async function applyNextcloudUpdate(
  app: AppEntry,
  appsDir: string,
  newVersion: string,
): Promise<void> {
  const workDir = await mkdtemp(path.join(tmpdir(), "nextcloud-update-"));

  try {
    const archiveName = `nextcloud-${newVersion}.zip`;
    const archiveUrl = `${DIST_BASE}/${archiveName}`;
    const archivePath = path.join(workDir, archiveName);

    await downloadFile(archiveUrl, archivePath);
    await verifyChecksum(archiveUrl, archiveName, archivePath);

    const extractDir = path.join(workDir, "extracted");
    await mkdir(extractDir);
    await extract(archivePath, { dir: extractDir });

    const [topLevelEntry] = await readdir(extractDir);
    if (!topLevelEntry) {
      throw new Error(`Archive ${archiveName} did not contain any files`);
    }

    const sourceDir = path.join(extractDir, topLevelEntry);
    const targetDir = path.join(appsDir, app.folder);

    await cp(sourceDir, targetDir, {
      recursive: true,
      force: true,
      filter: (source) => {
        const relative = path.relative(sourceDir, source);
        if (relative !== path.join("config", "config.php")) return true;
        return !existsSync(path.join(targetDir, relative));
      },
    });
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

/**
 * Nextcloud's .sha256 files list checksums for both the .zip and its
 * .metadata sibling on separate lines, so - unlike phpMyAdmin's single-entry
 * checksum file - the matching line has to be picked out by filename.
 */
async function verifyChecksum(
  archiveUrl: string,
  archiveName: string,
  archivePath: string,
): Promise<void> {
  const response = await fetch(`${archiveUrl}.sha256`);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch checksum for ${archiveUrl}: ${response.status} ${response.statusText}`,
    );
  }

  const line = (await response.text())
    .split("\n")
    .find((entry) => entry.trim().endsWith(archiveName));
  const expected = line?.trim().split(/\s+/)[0];
  if (!expected) {
    throw new Error(`Checksum file for ${archiveUrl} had no entry for ${archiveName}`);
  }

  assertChecksum(archiveUrl, expected, await sha256File(archivePath));
}
